In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('C:/Users/Admin/Untitled Folder 6/Iris.csv')

In [ ]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
df.shape

(150, 6)

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
x=df.drop(['Id', 'Species'], axis=1)

In [ ]:
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [ ]:
x.shape

(150, 4)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['Species']=label.fit_transform(df['Species'])

In [ ]:
y=df['Species']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int32

In [ ]:
print(y.shape)

(150,)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest=train_test_split(x,y,test_size=0.2, random_state=0)

In [ ]:
xtrain.shape

(120, 4)

In [ ]:
xtest.shape

(30, 4)

In [ ]:
ytrain.shape

(120,)

In [ ]:
ytest.shape

(30,)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [ ]:
model.fit(xtrain, ytrain)

GaussianNB()

In [ ]:
ypred=model.predict(xtest)

In [ ]:
model.score(xtest, ytest)

0.9666666666666667

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

In [ ]:
cm=confusion_matrix(ytest, ypred)
print(cm)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]

In [ ]:
accuracy = accuracy_score(ytest,ypred)
precision =precision_score(ytest,ypred,average='micro')
recall =  recall_score(ytest,ypred,average='micro')
f1 = f1_score(ytest,ypred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

Confusion matrix for Naive Bayes
 [[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
accuracy_Naive Bayes: 0.967
precision_Naive Bayes: 0.967
recall_Naive Bayes: 0.967
f1-score_Naive Bayes : 0.967

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

In [ ]:
lr_accuracy = accuracy_score(ytest, ypred)

In [ ]:
lr_precision = precision_score(ytest, ypred, average='micro')
lr_recall = recall_score(ytest, ypred, average='micro')
lr_f1 = f1_score(ytest, ypred, average='micro')

In [ ]:
print('Accuracy_Logistic Regression: %.3f' % lr_accuracy)
print('Precision_Logistic Regression: %.3f' % lr_precision)
print('Recall_Logistic Regression: %.3f' % lr_recall)
print('F1-score_Logistic Regression: %.3f' % lr_f1)

Accuracy_Logistic Regression: 0.967
Precision_Logistic Regression: 0.967
Recall_Logistic Regression: 0.967
F1-score_Logistic Regression: 0.967

In [ ]:
print("\nClassification Report:\n")
print(classification_report(ytest,ypred))

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30